name: Publish Subgraphs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  update_version:
    name: Update synthetix in contracts-interface
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: set version
        run: |
          # there are 3 possible values we will find version number
          export theversion=${${{ github.event.inputs.version }}:-bump}
          echo "Resolved version $theversion"
          echo "new_version=$theversion" >> $GITHUB_ENV
      - name: build
        run: |
          npm ci
      - name: deploy subgraphs
        run: |
          graph auth --product hosted-service ${{ secrets.GRAPH_TOKEN }}
          graph deploy --product hosted-service
      - name: Push changes
        run: git push
      - name: Notify dApps
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN_DAPPS }}" --request POST --data "{\"event_type\": \"update-dependency\", \"client_payload\": {\"version\": \"${{ github.event.client_payload.version }}\"}}" https://api.github.com/repos/Synthetixio/staking/dispatches
          curl -H "Authorization: token ${{ secrets.GH_TOKEN_DAPPS }}" --request POST --data "{\"event_type\": \"update-dependency\", \"client_payload\": {\"version\": \"${{ github.event.client_payload.version }}\"}}" https://api.github.com/repos/Kwenta/kwenta/dispatches
